
CREATE TABLE employee_details (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_email VARCHAR(255) NOT NULL,
    employee_join_date DATE NOT NULL,
    employee_location VARCHAR(255),
    employee_name VARCHAR(255),
    employee_phone VARCHAR(10) NOT NULL,
    employee_post VARCHAR(255),
    employee_sal FLOAT,
    PRIMARY KEY (employee_id)
);
create table user_details (
        user_id bigint not null,
        create_at date not null,
        user_email varchar(100) not null,
        user_name varchar(255) not null,
        user_password varchar(255) not null,
        update_at date not null,
        primary key (user_id)
    );
    
INSERT INTO employee_details (employee_email, employee_join_date, employee_location, employee_name, employee_phone, employee_post, employee_sal) VALUES 
('john.doe@example.com', DATE '2024-01-01', 'New York', 'John Doe', '1234567890', 'Software Engineer', 75000.00),
('jane.smith@example.com', DATE '2024-02-15', 'Los Angeles', 'Jane Smith', '0987654321', 'Product Manager', 85000.00),
('mike.jones@example.com', DATE '2024-03-20', 'Chicago', 'Mike Jones', '1122334455', 'Data Analyst', 70000.00),
('sara.connor@example.com', DATE '2024-04-10', 'San Francisco', 'Sara Connor', '2233445566', 'Project Manager', 90000.00),
('tom.hard@example.com', DATE '2024-05-25', 'Miami', 'Tom Hardy', '3344556677', 'Web Developer', 65000.00),
('anna.taylor@example.com', DATE '2024-06-30', 'Seattle', 'Anna Taylor', '4455667788', 'UI/UX Designer', 72000.00),
('robert.brown@example.com', DATE '2024-07-05', 'Austin', 'Robert Brown', '5566778899', 'QA Engineer', 68000.00),
('lisa.white@example.com', DATE '2024-08-15', 'Denver', 'Lisa White', '6677889900', 'HR Manager', 80000.00),
('david.green@example.com', DATE '2024-09-01', 'Boston', 'David Green', '7788990011', 'DevOps Engineer', 95000.00),
('emma.black@example.com', DATE '2024-10-10', 'Orlando', 'Emma Black', '8899001122', 'Marketing Specialist', 60000.00);
